language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "gomint-github"

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

cache:
  directories:
    - '$HOME/.m2/repository'
