name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn -B package deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    - run: mkdir -p ./release/modules && cp -r ./gomint-server/target/modules/* ./release/modules/ && cd release && zip -r server.zip ./
    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GoMint Server
        path: ./release/server.zip
    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
        username: gomint
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gomint/gomint
        tags: ${{ github.sha }}
    - uses: release-drafter/release-drafter@v5
      name: Create or update release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.S3_SECRET_KEY}}
        aws_bucket: gomint-artifacts
        source_dir: ./release/server.zip
        destination_dir: latest.zip
