name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@fork-support
        with:
          GITHUB_TOKEN: ${{ secrets.GOMINTY_TOKEN }}
          reviewers: true
          labels: merge
          blocking_labels: do not merge
          checks_enabled: true
          method: merge
